# fly.toml app configuration file generated for server-late-sun-2066 on 2025-10-15T17:57:56+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-late-sun-2066'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
